### ISSUE TITLE
Issue with function calling using tools parameter

### ISSUE THREAD

**Issue by trathi05** [daveebbelaar/langchain-experiments#16]
Hi Dave. I am using your `openai_function_calling.py` example to understand the function calling functionality. I see that it is a little outdated and I tried to update the code. Apart from changing `ChatCompletion.create` to `chat.completion.create`, the main change is the use of `tools` parameter instead of `functions` (and `tool_choice` instead of `function_call`). It seems to run fine except for the part where the function result is integrated into the API call (`second_completion` parameter in the code -- towards the very end). The main change is the use of `tool` as a `role` instead of `function` as a `role`. Could you please guide me on what exactly I am doing wrong? The updated code is as follows:

```
import json
from openai import OpenAI
from datetime import datetime, timedelta

client = OpenAI()

# --------------------------------------------------------------
# Ask ChatGPT a Question
# --------------------------------------------------------------

completion = client.chat.completions.create(
    model="gpt-3.5-turbo-0613",
    messages=[
        {
            "role": "user",
            "content": "When's the next flight from Amsterdam to New York?",
        },
    ],
)

output = completion.choices[0].message.content
print("\n")
print(output)
print("\n")

# --------------------------------------------------------------
# Use OpenAI’s Function Calling Feature
# --------------------------------------------------------------

tools = [
  {
    "type": "function",
    "function": {
      "name": "get_flight_info",
      "description": "Get flight information between two locations",
      "parameters": {
        "type": "object",
        "properties": {
          "loc_origin": {
            "type": "string",
            "description":  "The departure airport, e.g. DUS",
          },
          "loc_destination": {
                    "type": "string",
                    "description": "The destination airport, e.g. HAM",
          }
        },
        "required": ["loc_origin", "loc_destination"],
      },
    }
  }
]

user_prompt = "When's the next flight from Amsterdam to New York?"

completion = client.chat.completions.create(
    model="gpt-3.5-turbo-0613",
    messages=[{"role": "user", "content": user_prompt}],
    # Add function calling
    tools=tools,
    tool_choice="auto",  # specify the function call
)

# It automatically fills the arguments with correct info based on the prompt
# Note: the function does not exist yet

output = completion.choices[0].message.tool_calls[0]
print("\n")
print(output)
print("\n")

# --------------------------------------------------------------
# Add a Function
# --------------------------------------------------------------


def get_flight_info(loc_origin, loc_destination):
    """Get flight information between two locations."""

    # Example output returned from an API or database
    flight_info = {
        "loc_origin": loc_origin,
        "loc_destination": loc_destination,
        "datetime": str(datetime.now() + timedelta(hours=2)),
        "airline": "KLM",
        "flight": "KL643",
    }

    return json.dumps(flight_info)


# Use the LLM output to manually call the function
# The json.loads function converts the string to a Python object

origin = json.loads(output.function.arguments).get("loc_origin")
destination = json.loads(output.function.arguments).get("loc_destination")
params = json.loads(output.function.arguments)
type(params)

print("\n")
print(origin)
print(destination)
print(params)
print("\n")

# Call the function with arguments

chosen_function = eval(output.function.name)
flight = chosen_function(**params)

print("\n")
print(flight)
print("\n")

# --------------------------------------------------------------
# Add function result to the prompt for a final answer
# --------------------------------------------------------------

# The key is to add the function output back to the messages with role: function
second_completion = client.chat.completions.create(
    model="gpt-3.5-turbo-0613",
    messages=[
        {"role": "user", "content": user_prompt},
        {"role": "tool", "tool_call_id": output.id, "content": flight}, # this line seems to be the problem
    ],
    tools=tools,
)
response = second_completion.choices[0].message.content
print("\n")
print(response)
print("\n")
```

The error I run into is as follows:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Mac/openai-env/lib/python3.12/site-packages/openai/_utils/_utils.py", line 272, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Mac/openai-env/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 645, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/Mac/openai-env/lib/python3.12/site-packages/openai/_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Mac/openai-env/lib/python3.12/site-packages/openai/_base_client.py", line 853, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/Mac/openai-env/lib/python3.12/site-packages/openai/_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.", 'type': 'invalid_request_error', 'param': 'messages.[1].role', 'code': None}}
```

Thank you! Any help is really appreciated.

**Comment by deepakmkoshy** [comment]
I was following the tutorial, and your question helped me migrate until I encountered the same hurdle you did. 

I managed to find the solution by following OpenAI's official function-calling guide. We need to append the assistant's response while requesting the second completion:

```
user_prompt = "When's the next flight from Amsterdam to New York?"

completion = client.chat.completions.create(
    model="gpt-3.5-turbo-0613",
    messages=[{"role": "user", "content": user_prompt}],
    # Add function calling
    tools=tools,
    tool_choice="auto",  # specify the function call
)

# Add this:
response_message = completion.choices[0].message
# Then rest of the code as usual, and when calling second completion:

second_completion = client.chat.completions.create(
    model="gpt-3.5-turbo-0125",
    messages=[
        {"role": "user", "content": user_prompt},
        # Append response_message here so that the model can track the response made by the assistant
        response_message,
        {"role": "tool", "tool_call_id": output.id, "content": flight},
    ],
    tools=tools,
)

response = second_completion.choices[0].message.content
print(response)
```

**Comment by trathi05** [comment]
>We need to append the assistant's response while requesting the second completion

Yes, I did figure that out after some tries. I almost forgot I had raised an issue here for that. But thanks anyway :)
